# Auto Label Git Action Config
# 'label_name'
#   - path_of_diff/where/code_lives/to_base_label_upon

# Any change to any file in .github/workflows
'GitHub Actions':
  - '.github/workflows/*'

# Any change to the docker-compose file or any dockerfile in the repo
'Docker':
  - '**/Dockerfile'
  - 'docker-compose.yml'
  - 'docker/**/*'

# Any changes to file of subfolders in app/Server
'Backend':
  - 'app/server/**/*'
  
# Any changes to file of subfolders in app/Agri.*
'Frontend':
  - 'app/Agri.*/**/*'

# Any changes to file of subfolders in /tests
'Testing':
  - 'functional-tests/**/*'

# Any change to any file in any directory with a .env in name
'Environment Variables':
  - '**/*.env*'
