apiVersion: v1
kind: Template
metadata: 
  creationTimestamp: null
  name: certbot
parameters:
    # https://crontab.guru/every-6-hours 
  - name: 'CERTBOT_CRON_SCHEDULE'
    required: false
    value: "0 */6 * * *"
    # Let's Encrypt Stage environment will help with non-prod cert renewals, so you don't limits
  - name: 'CERTBOT_STAGING'
    required: false
    value: "false"
    # in environments using wildcard *.pathfinder cert, you might want to create the cronjob for consistency, but suspend it
  - name: 'CERTBOT_SUSPEND_CRON'
    required: false
    value: "false"
  - name: 'DEBUG'
    required: false
    value: "false"
  - name: 'DELETE_ACME_ROUTES'
    required: false
    value: "true"
  - name: 'EMAIL'
    required: true
  - name: 'IMAGE_NAMESPACE'
    required: true
    value: ""
  - name: 'SOURCE_IMAGE_NAME'
    required: false
    value: "certbot"
  - name: 'TAG_NAME'
    required: false
    value: "latest"    

objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: certbot
    creationTimestamp: null
    name: certbot
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    labels:
      app: certbot
    creationTimestamp: null
    name: certbot_edit
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: certbot
#PVC
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: certbot
    creationTimestamp: null
    name: certbot
  spec:
    storageClassName: netapp-file-standard
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
  status: {}
#CROBJOB
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    creationTimestamp: null
    labels:
      app: certbot
    name: certbot
  spec:
    concurrencyPolicy: Replace
    failedJobsHistoryLimit: 3
    successfulJobsHistoryLimit: 3
    startingDeadlineSeconds: 60
    jobTemplate:
      metadata:
        creationTimestamp: null
      spec:
        backoffLimit: 6
        activeDeadlineSeconds: 300
        parallelism: 1
        completions: 1
        template:
          metadata:
            creationTimestamp: null
            labels:
              app: certbot
          spec:
            containers:
            - name: certbot
              image: "docker-registry.default.svc:5000/${IMAGE_NAMESPACE}/${SOURCE_IMAGE_NAME}:${TAG_NAME}"
              imagePullPolicy: Always
              env:
                - name: CERTBOT_EMAIL
                  value: '${EMAIL}'
                - name: CERTBOT_DEBUG
                  value: '${DEBUG}'
                - name: CERTBOT_DELETE_ACME_ROUTES
                  value: '${DELETE_ACME_ROUTES}'                                    
                - name: CERTBOT_STAGING
                  value: '${CERTBOT_STAGING}'  
              resources:
                requests:
                  cpu: 100m
                limits:
                  cpu: 200m
              volumeMounts:
                - mountPath: /etc/letsencrypt
                  name: certbot-config
            restartPolicy: Never      
            serviceAccountName: certbot
            volumes:
              - name: certbot-config
                persistentVolumeClaim:
                  claimName: certbot               
    schedule: '${CERTBOT_CRON_SCHEDULE}'
    suspend: '${{CERTBOT_SUSPEND_CRON}}'
  status: {}
#end cron job